# Generated by Django 6.0 on 2026-06-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0016_alter_player_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField(help_text='This adds this amount of health to the ball before applying to percentage bonus')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='bd_models.special')),
            ],
        ),
    ]
